### ISSUE TITLE
Deploy Project on Vercel with /docs/index.html as Main Page?

### ISSUE THREAD

**Issue by jamiecropley** [paganotoni/doco#29]
How can I deploy a project on Vercel such that the index.html file in the /docs directory serves as the main page of the site?

I see you provide instructions for Cloudflare and Github Pages.

I can't translate the instructions well, I am a bit new to this.

But I like golang usually on backend because its simple to use, never attempted to use it on front end only.

**Comment by paganotoni** [comment]
@jamiecropley thanks for posting this. I will work on this one soon and add a guide for Vercel.

**Comment by jamiecropley** [comment]
> @jamiecropley thanks for posting this. I will work on this one soon and add a guide for Vercel.

Keep this open as well, I will have a play around with it and update anything new I find here if it helps. My key concern with vercel, I have a paid plan budget $20 a month, I pay for this so I can build many sites for commercial use, but my main gripe is not always deploying in such a complex manner because that's how you end up with multiple charges, thus where it gets confusing for me more than anything.

**Comment by paganotoni** [comment]
It would be great to read any findings you encounter. I gave it a brief try and made some progress with GitHub actions. Ended up here:

```lml
      # Push our generated site to vercel
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
        # Here I'm copying the Doco output as the CLI tool expects the output to live 
        # on .vercel/output
      - name: Copy output
        run: mkdir -p .vercel/output && cp -r public/* .vercel/output
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
```

However, it still complaining about some vercel configuration.

**Comment by jamiecropley** [comment]
I know at the basic level I can build locally, then simply manually deploy to github which in turn auto deploys to vercel, thus it is only deploying the static HTML files then, but would ideally want something for docs where I don't have to keep running so many build commands etc... every time I update a markdown file.

**Comment by jamiecropley** [comment]
> It would be great to read any findings you encounter. I gave it a brief try and made some progress with GitHub actions. Ended up here:
> 
> ```
>       # Push our generated site to vercel
>       - name: Install Vercel CLI
>         run: npm install --global vercel@latest
>         
>         # Here I'm copying the Doco output as the CLI tool expects the output to live 
>         # on .vercel/output
>       - name: Copy output
>         run: mkdir -p .vercel/output && cp -r public/* .vercel/output
>       - name: Pull Vercel Environment Information
>         run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
>       - name: Deploy Project Artifacts to Vercel
>         run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
> ```
> 
> However, it still complaining about some vercel configuration.

I think this could be a good key to it https://vercel.com/docs/projects/project-configuration but I don't usually add these in most my sites added on there, it will generate them automatically.

**Comment by jamiecropley** [comment]
So I had to make my own document generator in golang to understand more how vercel would achieve something like this. I don't think honestly vercel works straight forward like this with a focus more on node / next js kinda side of things rather than go long. Ideally the best way is to generate the docs to HTML first then deploy those static files once generated.

**Comment by paganotoni** [comment]
Yes. You can initialize your docs locally with `doco init` and then run `doco build` to generate the public folder; that public folder will have the resulting HTML. If you want to see the changes to your docs, you can run them locally with `doco serve` which rebuilds the documentation as you change the documents.

**Comment by jamiecropley** [comment]
> Yes. You can initialize your docs locally with `doco init` and then run `doco build` to generate the public folder; that public folder will have the resulting HTML. If you want to see the changes to your docs, you can run them locally with `doco serve` which rebuilds the documentation as you change the documents.

Yeah, so usually Vercel is very good at this if the main framework is javascript driven, despite my best efforts and tests it just won't pick up anything golang, you need to just build it locally then deploy the locally generated HTML files and such this way.

**Comment by paganotoni** [comment]
Cool. Let's review this later on. Thanks for bringing this up. I learned a bit about Vecel.
